### ISSUE TITLE
Cool project - any suggestions to get vcom value?

### ISSUE THREAD

**Issue by kimmobrunfeldt** [adzialocha/it8951-video#1]
Hi! I've been playing with the usb based controlling using https://sr.ht/~martijnbraam/it8951/ C code as the basis. I wasn't able to get the current vcom value using [this code](https://github.com/kimmobrunfeldt/eink-weather-display/blob/d89224e86e64a8672f0d5d1bbf102d12b04b51b7/rasp/usb-it8951/main.c#L189). Have you successfully queried the vcom value? The USB programming pdf sheet had an example command:

```c
unsigned char get_vcom_cmd[16] = {
  0xfe, // Customer command.
  0x00,
  0x00,
  0x00,
  0x00,
  0x00,
  0xa3,  // PMIC (Power Management Integrated Circuits) command.
  0x00,
  0x00,
  0x00,   // Do Set VCom? (0 – no, 1 – yes)
  0x00,
  0x00,
  0x00,
  0x00,
  0x00,
  0x00,
};
```

but it didn't describe the return shape or length in bytes.

As a reference, Waveshare has a GPIO based C [code example](https://github.com/waveshare/IT8951-ePaper/blob/master/Raspberry/lib/e-Paper/EPD_IT8951.c#L268).

**Comment by adzialocha** [comment]
Hey @kimmobrunfeldt!  :wave: 

I just made an experiment and could retreive the data with the command you've mentioned. The result you're receiving is a "word" (that is two bytes, or 16 bit).

The VCOM value of my display is `-1.58`, which is represented as `1580` (decimal) or `062c` (hex). When I run the `0xa3` command I receive `062c` :+1: - this is the code I've used:

```rust
let data = [
    CUSTOMER_CMD, // 0xfe
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    PMIC_CONTROL_CMD, // 0xa3
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
];

// https://github.com/adzialocha/it8951-video/blob/main/src/usb.rs#L47
let result: u16 = self
    .connection
    .read_command(&data, bincode::options().with_big_endian())?;

println!("{:x}", result); // 062c
```

**Comment by kimmobrunfeldt** [comment]
@adzialocha ok awesome, thanks for testing!
Then it seems like my C code might have an issue with reading data.

**Comment by kimmobrunfeldt** [comment]
Finally figured it out with the help of your example code. I didn't spot the "FROM" vs "TO" difference before, now with correct communication direction it works: https://github.com/kimmobrunfeldt/eink-weather-display/commit/84b60bf90769ac7c972e3cf19a527ec291fe7213

**Comment by adzialocha** [comment]
Super ☺️
